### ISSUE TITLE
Raises a warning on MacOS Catalina

### ISSUE THREAD

**Issue by askoretskiy** [dsiebel/make-bootstrap#4]
When executed on the macOS Catalina, it always raises a warning:

```
$ make true
.bootstrap.mk:54: "Can't detect git root. GITROOT variable will be empty"
true
```

Here is my make version:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

I understand that it is an older BSD version, but it would be nice if that works on MacOS out of the box.

Somehow the problem is on these lines:
```
GITROOT := $(shell git rev-parse --show-toplevel 2>/dev/null)
ifneq ($(.SHELLSTATUS),0)
  $(warning "Can't detect git root. GITROOT variable will be empty")
endif
```

Maybe the script should be changed or removed at all.

**Comment by Zebradil** [comment]
@askoretskiy, there is no such line in this library, `GITROOT` is added in my fork.

**Comment by askoretskiy** [comment]
Sorry, this should have been filled on https://github.com/Zebradil/make-bootstrap
